### ISSUE TITLE
[BUG] 
Cursor Speed Too Fast

### ISSUE THREAD

**Issue by jvenable27** [urikdev/Urik#380]
**Device Model**
Pixel 9a

**Android Version**
GrapheneOS 2025121701

**App Version**
0.12.0 beta

**Keyboard Language** (optional)
English

**Steps to Reproduce**
1. Long press space bar
2. Slide R or L
3. 

**Expected Behavior**
Cursor moves at a slow pace in order to place it at a  precise point

**Actual Behavior**
cursor moves at a very fast pace making it impossible to stop/place it where desired

**Logs** (optional)

**Additional Context** (optional)

**Comment by urikdev** [comment]
Hey there, this should be fixed in the latest release. Please let us know!

**Comment by jvenable27** [comment]
Unfortunately, still no change for me. Still very difficult to get the cursor to stop at (or close to) a specific character. It does seem a bit slower, but not near enough.

**Comment by urikdev** [comment]
@jvenable27 Hey! We've made some more tweaks to this in the latest release, could you let us know it feels now?

**Comment by feuersternX** [comment]
Feels good

**Comment by urikdev** [comment]
Shoot! Okay, we may need to send you a special debug build with some logs. We'll connect!

**Comment by feuersternX** [comment]
Oh uh sorry, I confused the issue with your comment in #391. @jvenable27 is right, it doesn't work anymore and only brings up the punctuation menu, and this only works with the space key and not when you press the "." key as described as an alternative  in #391.
